sudo: false
language: python
python:
    - "3.6"
    - "3.7"
addons:
  postgresql: "9.4"
env:
  - DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install pip setuptools --upgrade
  - pip install tox tox-travis coveralls
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database pgallery;' -U postgres
script:
  - tox
after_success:
  - if [ "$TOXENV" = "py37-coverage" ]; then coveralls; fi
