language: python
python:
  - "2.7"
env:
  - DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database pgallery;' -U postgres
script: coverage run runtests.py
after_success:
  - coveralls
