language: python
python:
  - "2.7"
addons:
    postgresql: "9.3"
env:
  - DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install pip setuptools --upgrade
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database pgallery;' -U postgres
script:
    - export PYTHONPATH=$PYTHONPATH:`pwd`
    - make coverage
after_success:
  - coveralls
