sudo: false
language: python
addons:
  postgresql: "9.4"
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
env:
  - TOXENV=py27-dj18 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=py33-dj18 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=py34-dj18 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=py27-dj19 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=py34-dj19 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=py35-dj19 DATABASE_USER="postgres" DATABASE_PASSWORD=""
  - TOXENV=coverage DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install pip setuptools --upgrade
  - pip install tox
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database pgallery;' -U postgres
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
