language: python
addons:
    postgresql: "9.4"
env:
  - DATABASE_USER="postgres" DATABASE_PASSWORD=""
install:
  - pip install pip setuptools --upgrade
  - pip install -r test_requirements.txt
before_script:
  - psql -c 'create extension hstore;' -U postgres -d template1
  - psql -c 'create database pgallery;' -U postgres
script:
    - export PYTHONPATH=$PYTHONPATH:`pwd`
    - make test
